name: aio-iot-app
base: core18
version: "0.1"
summary: All-In-One IoT Solution for Condition Monitoring
description: |
    Compilation of the best open source IoT software available. NodeRED, InfluxDB and
    Grafana all together and pre-configured, ready for your needs.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

# enable once everything is up and running
# architectures:
#   - build-on: [arm64, amd64]

apps:
    influx:
        command: bin/influx
        plugs: [network]
    influxd:
        command: bin/influxd --config=$SNAP_DATA/influxdb/conf/influxdb.conf
        daemon: simple
        restart-condition: on-failure
        restart-delay: 5s
        plugs: [network-bind, network]
    grafana-server:
        command: bin/grafana-server --config=$SNAP_DATA/grafana/conf/defaults.ini --homepath=$SNAP
        daemon: simple
        restart-condition: on-failure
        restart-delay: 5s
        plugs: [network-bind, network]
    node-red:
        command: bin/startNR
        daemon: simple
        restart-condition: on-failure
        restart-delay: 5s
        plugs:
            - bluez
            - bluetooth-control
            - home
            - network-bind
            - network
            - network-observe
            - removable-media

parts:
    dependencies:
        plugin: nil
        stage-snaps:
            - influxdb-ijohnson/latest/stable
            - grafana/7/stable
            - node-red/latest/stable

    grafana-config:
        plugin: dump
        source: ./grafana/
        organize: 
            "defaults.ini" : dump/

    influx-config:
        plugin: dump
        source: ./influxd/
        organize: 
            "influxdb.conf": dump/
