name: aio-iot-app
base: core18
version: '1.1.0'
icon: snap/icons/icon.png
summary: All-In-One IoT Software Solution for Condition Monitoring
description: |
    The best open source IoT software available, bundled together as a single snap.
    NodeRED, InfluxDB and Grafana all together and pre-configured, ready to use together
    with the whole ctrlX Ecosystem.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
    create-db:
        command: bin/influx -execute "CREATE DATABASE db WITH DURATION 40d REPLICATION 1 NAME forty_days"
        plugs: [network, home]
        daemon: simple
        restart-condition: never
    influx:
        command: bin/influx
        plugs: [network, home]
    influxd:
        command: bin/influxd --config $SNAP_DATA/influxdb/conf/influxdb.conf
        daemon: simple
        restart-condition: on-failure
        restart-delay: 5s
        plugs: [network-bind, network]
        after:
          - create-db
    grafana-server:
        command: bin/grafana-server --config $SNAP_DATA/grafana/conf/defaults.ini --homepath $SNAP
        daemon: simple
        restart-condition: on-failure
        restart-delay: 5s
        plugs: [network-bind, network]
    node-red:
        command: bin/startNR
        daemon: simple
        restart-condition: on-failure
        restart-delay: 5s
        plugs:
            - bluez
            - bluetooth-control
            - home
            - network-bind
            - network
            - network-observe
            - serial-port

parts:
    dependencies:
        plugin: nil
        stage-snaps:
            - influxdb-ijohnson/latest/stable
            - node-red/latest/stable
            - on amd64: [grafana/latest/stable]
            - on arm64: [grafana/latest/beta]
        override-prime: |
            npm install node-red-contrib-influxdb node-red-contrib-ctrlx-automation node-red-dashboard
            snapcraftctl prime

    grafana-config:
        plugin: dump
        source: ./grafana
        organize: 
            "defaults.ini" : dump/

    influx-config:
        plugin: dump
        source: ./influxd
        organize: 
            "influxdb.conf": dump/

    ctrlx-config:
        plugin: dump
        source: ./configs
        organize: 
            'package-assets/*': package-assets/aio-iot-app/

slots:
    package-assets:
        interface: content
        content: package-assets
        source:
            read:
            - $SNAP/package-assets/aio-iot-app

plugs:
  active-solution:
    content: solutions
    interface: content
    target: $SNAP_COMMON/solutions
